Styles contact-us
Valeriia-Sirenko/Project-WatchCharm pull request #5
Opened 2024-09-06 13:46 UTC by AlinaPolishchuk-l

2024-09-06 21:34 UTC, Valeriia-Sirenko commented on src/partials/contact-us.html
> +            src="../img/about-us/contant-us-clock-monitor.png"
переплутала about-us та contant-us

2024-09-06 22:44 UTC, Valeriia-Sirenko requested changes
одненька помилочка)

2024-09-07 07:24 UTC, AlinaPolishchuk-l commented on src/partials/contact-us.html
> +            src="../img/about-us/contant-us-clock-monitor.png"
виправила

2024-09-07 13:08 UTC, Valeriia-Sirenko approved these changes

2024-09-07 13:16 UTC, Valeriia-Sirenko approved these changes

2024-09-07 13:48 UTC, Valeriia-Sirenko approved these changes

2024-09-07 13:48 UTC, merged

2024-09-07 17:51 UTC, Valeriia-Sirenko commented on src/partials/contact-us.html
> +<section class="contact-us">
<section class="contact-us" **id="contact-us"**>